esphome:
  name: power-meter
  friendly_name: power-meter

esp32:
  board: esp32-s2-saola-1
  framework:
    type: arduino

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa="

ota:
  password: "aaaaaaaa"

wifi:
  ssid: aaaaaaaaaa
  password: aaaaaaaaa

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test-Power-Meter"
    password: "aaaaaaaa"

captive_portal:

external_components:
  - source:
      type: local
      path: ./my_components

uart:
  tx_pin: GPIO21
  rx_pin: GPIO39
  baud_rate: 4800
  parity: NONE
  stop_bits: 2

sensor:
  - platform: bl0939
    update_interval: 30s
    voltage:
      name: 'BL0939 Voltage'
    current_1:
      name: 'BL0939 Current 1'
    current_2:
      name: 'BL0939 Current 2'
    active_power_1:
      name: 'BL0939 Active Power 1'
    active_power_2:
      name: 'BL0939 Active Power 2'
    energy_1:
      name: 'BL0939 Energy 1'
    energy_2:
      name: 'BL0939 Energy 2'
    energy_total:
      name: 'BL0939 Energy Total'